services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: polestarfinder
    ports: ["5432:5432"]
    volumes:
      - db_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports: ["8080:8080"]

volumes:
  db_data:
