filters = {
    # "Snow": {"Exterior": "70700"},
    # "Space": {"Exterior": "71700"},
    # "Thunder": {"Exterior": "72800"},
    # "Void": {"Exterior": "01900"},
    # "Magnesium": {"Exterior": "72900"},
    # "Midnight": {"Exterior": "72300"},
    # "Moon": {"Exterior": "72700"},
    # "Jupiter": {"Exterior": "73600"},
    # "Performance": {"Package": "1010"},
    # "Pilot": {"Package": "1040"},
    # "Plus": {"Package": "1050"},
    # "Long range Dual motor - AWD": {"Motor": "ED"},
    # "Long range Dual motor - All Wheel Drive (AWD)": {"Motor": "FD"},
    # "Long range Dual motor with Performance pack - AWD": {"Motor": "ET"},
    # "Long range Single motor ": {"Motor": "EG"},
    # "Long range Single motor - Rear Wheel Drive (RWD) ": {"Motor": "FE"},
    # "Slate WeaveTech with Black Ash deco": {"Interior": "RFA000"},
    # "Charcoal WeaveTech with Black Ash deco": {"Interior": "RF8000"},
    # "Charcoal Embossed Textile with 3D Etched deco": {"Interior": "R60000"},
    # "Zinc Embossed Textile with 3D Etched deco": {"Interior": "R6B000"},
    # "Ventilated Nappa leather Barley with reconstructed wood deco": {
    #     "Interior": "RCC000"
    # },
    # "Ventilated Nappa leather Zinc with Light Ash deco": {"Interior": "RCZ300"},
    # "Charcoal MicroSuede textile with Black ash deco": {"Interior": "BST230"},
    # "BST Edition 230": {"Edition": "BST Edition 230"},
    # "BST Edition 270": {"Edition": "BST Edition 270"},
    # '19" 5-V Spoke Black Diamond Cut Alloy Wheels - Summer Tire': {"Wheels": "R14B"},
    # "19'' 5-Double Spoke Black Diamond Cut Alloy Wheel": {"Wheels": "R184"},
    # '20" 4-V Spoke Black Diamond Cut Alloy Wheels': {"Wheels": "001147"},
    # '20" 4-Y Spoke Black Polished Forged Alloy Wheels - Summer Tire': {
    #     "Wheels": "XPFWHE"
    # },
    # '20" Pro - All-Season Tires': {"Wheels": "001257"},
    # "21'' Gloss Black Diamond Cut Alloy Wheel BST edition": {"Wheels": "XPEWHE"},
    "Certified PreOwned": {"CycleState": "CertifiedPreOwned"},
    "PreOwned": {"CycleState": "PreOwned"},
    "New": {"CycleState": "New"},
}
