name: Deploy Lambda (single target)
on:
  push:
    branches: [dev, main]

env:
  PYTHON_VERSION: "3.12"
  BUILD_DIR: "build"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Build artifact (Linux wheels)
      run: |
        rm -rf $BUILD_DIR artifact.zip
        mkdir -p $BUILD_DIR
        pip install --upgrade pip
        pip install -r requirements.txt -t $BUILD_DIR
        cp -R jobs scraper database $BUILD_DIR/
        cd $BUILD_DIR && zip -r ../artifact.zip .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Update Lambda code
      run: |
        aws lambda update-function-code \
          --function-name ${{ secrets.LAMBDA_TARGET_NAME }} \
          --zip-file fileb://artifact.zip
